chore: add all-ok job on ci (#153)
This makes it easier to choose which tests are required to merge a PR.
Same pattern as in Tesseract Core.

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -74,3 +74,19 @@ jobs:
           slug: pasteurlabs/tesseract-jax
           files: coverage*.xml
           fail_ci_if_error: true
+
+  all-ok:
+    if: always()
+    needs: [tests]
+
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Check for errors
+        run: |
+          if [[ "${{ needs.tests.result }}" != "success" && "${{ needs.tests.result }}" != "skipped" ]]; then
+            echo "Tests failed"
+            exit 1
+          fi
+
+          echo "All tests passed!"
